language: node_js
node_js:
- 10
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
install:
- yarn install
script:
- "$(yarn bin)/cypress run --record $RECORD_KEY"
dd:
  secure: V5/d4SuAhH372r/hJtRrSLL9QQ7YGxFZ36G61ezvptgISpzlwLAOKXHO/ioUx/GDHp0Q2slpwSTAcTmFYR68UovVLobCcKk8egZGraTpdBlqbFCCm68+PGmWoAuahcVLxVNGA8OZD3bdN6+6hEf1cSPaSyso8fEqSbWF0Lu4GuQdimnVRDKHGIYxtQbUuXjcob2dng9mLTZj3XCDbNTnM4uIAp45SE/oWCiCcpduHijqixOci83s3vTBQTgHEAGKwuGCvQu2KKYQ4bIzPh3/pvZjSTrnsZU2MAMjaCGcjSpUMzKacLLb+sKBcXHr1ByboSItb7zZDRm75dPXZJS3Q6tUyHtkSLZQO0h4aQTyaDcC3OdAObHcwuee84IvwsKuGYy5KcSMYzVkvKe55PX9pqYPPYJrIm3Gbp/Bugu6uxdDDkxfS0qc5IjKJy3IO5rx9eQrfWi268WFbFJo6B2/Qf0/YDJlBokcJUCKWJoSo4hGJ6A605NY5am4jPZn7S76w9VwtFsZCqIZQPB3U7pKBidu3y17MR4IHUOEwaSqJuLwv6OmjAvC5tbd74geis4cOeLbsr2n/3pbMNj4yVzB6Wu5oZJ2vOK5LfFvwQCYnCJ5o7DPD1yDFyeLWAwOgHdH4EPLqEey+cD7+fNA2rcc4Q4nFL2XeAkXs1VFkQcJTho=
