name: InStock Monitor
on:
  schedule:
    - cron: '0 7,0 10, 0 20 * * *'
  push:
    branches:
      - main
job:
  Check-Stocks:
    runs-on: ubuntu-latest
    name: Check Stocks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-actions@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}